FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o mil-switchboard .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/mil-switchboard .
CMD ["./mil-switchboard"]
